### ISSUE TITLE
react-apollo beta won't minify with create-react-app build process

### ISSUE THREAD

**Issue by tavelli** [apollographql/react-apollo#1734]
**Intended outcome:**
npm run build compiles code

**Actual outcome:**
get the following build error

```
Failed to minify the code from this file:
./node_modules/react-apollo/parser.mjs:13
Read more here: http://bit.ly/2tRViJ9
```

**How to reproduce the issue:**
have  a basic create-react-app, add react-apollo beta and try to run "build" script.  

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Version**
"react-apollo": "2.1.0-beta.3"

**Comment by dsummersja** [comment]
solved by reverting version to "2.0.4", deleting node_modules, yarn/npm install -> run build

**Comment by tavelli** [comment]
ok i figured it had to do with beta, but i just started building a new app based off latest docs using apollo-boost and the newer components like <Query> so theres no going backwards for me 😄

**Comment by tells** [comment]
had to just comment out the uglify plugin (line 291) in `./node_modules/react-scripts/config/webpack.config.prod.js` to build and keep going for now.

**Comment by pantharshit00** [comment]
This needs to be fixed soon. I can even build.

**Comment by bodia-uz** [comment]
@tavelli you could revert 2.1.0-beta.2. CRA has not build problem with this version

**Comment by tavelli** [comment]
Ok thanks that's good tip. I don't need to build and deploy quite yet just
wanted to raise it so hopefully will be fixed before 2.1 final release

**Comment by fabien0102** [comment]
Quick & dirty fix:
```js
// package.json
"scripts": {
    "fix-react-apollo": "rimraf ./node_modules/react-apollo/*.mjs",
    "build": "npm run fix-react-apollo && react-scripts build"
  },
```

Just removing all the `*.mjs` files in react-apollo and no more problems! 🎉

**Comment by excitement-engineer** [comment]
This is being fixed in CRA in https://github.com/facebook/create-react-app/pull/4085

**Comment by excitement-engineer** [comment]
@jbaxleyiii seems to have fixed this in #1769. Expect this to come out really soon in the next release.

**Comment by tavelli** [comment]
@excitement-engineer just tested with 2.1.0-rc.3, working great!

**Comment by gaearon** [comment]
If your project is built with Create React App and not ejected, `react-scripts@1.1.2` should fix this.
Here is how to upgrade:

https://github.com/facebook/create-react-app/releases/tag/v1.1.2

Otherwise you can apply a [similar fix](https://github.com/facebook/create-react-app/pull/4085/files) yourself in your project config. Cheers!

**Comment by mjasnikovs** [comment]
@gaearon I did not fixed, i had to downgrade to react-apollo@2.1.1

**Comment by andrwsalcdo** [comment]
For others, 

I tried the other solutions. But, only @fabien0102's solution worked for me. 

version: 
"react-apollo": "^2.1.0-beta.3",

**Comment by keishon104** [comment]
I did "yarn install" and the error disappeared for me.
