### ISSUE TITLE
Apollo 2, useless re-render (twice render). Simple example, simple reproduction on codesandbox.

### ISSUE THREAD

**Issue by johnunclesam** [apollographql/react-apollo#1777]
# Reproduction: https://codesandbox.io/s/72kllvom21

**Intended outcome:**

Simple example of react-apollo. I have an Home component and a Players component. The Players has a graphql query to retrieve data.

**Actual outcome:**

The first time I have the good operation: it loads and I have two rendering because of `data > loading: true` value. The second time I go to that page it render two times but the content is the same and the `loading: false` both times.

I don't think this is the right way. **Where am I wrong?** https://codesandbox.io/s/72kllvom21

**How to reproduce the issue:**

https://codesandbox.io/s/72kllvom21

![image](https://user-images.githubusercontent.com/21275217/37255365-d3f2bb00-254b-11e8-8323-d0aecef44142.png)

**Version**

* apollo-client@2.2.6
* react-apollo@2.0.4

**Comment by ntomsic** [comment]
This looks like it might be a bug. The 1st time you hit the Players route it should rerender twice. If you click the Players link again, it only rerenders once (expected). However, if you click the Home route and then back to the Players route, it rerenders twice again with no changes in props.

**Comment by johnunclesam** [comment]
Maybe the same issue? https://github.com/apollographql/apollo-link-state/issues/217

**Comment by akiran** [comment]
I am trying to debug this issue and found that forceUpdate [here](https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L337) is responsible for second re-render

**Comment by johnunclesam** [comment]
@akiran why that force? Do you understand why?

**Comment by jbaxleyiii** [comment]
@johnunclesam thanks for the super clear reproduction! Fixed in the newest release and verified here https://codesandbox.io/s/o743y3yx25

**Comment by johnunclesam** [comment]
@jbaxleyiii thanks to you.

But using your last codesandbox I added `why-did-you-update` and there is still some problem:

**https://codesandbox.io/s/kmork0rxkv**

![image](https://user-images.githubusercontent.com/21275217/38036761-bcb8380c-32a7-11e8-9bb2-fda7683077ae.png)

![image](https://user-images.githubusercontent.com/21275217/38036783-c93a49ee-32a7-11e8-9fd6-099949bbf438.png)

**Comment by putuyoga** [comment]
bump! i've face kind similar issue @johnunclesam at first i guess it was my component. So i make it pure, still no luck.

![screen shot 2018-06-05 at 5 54 00 pm](https://user-images.githubusercontent.com/501990/40972006-85767034-68e9-11e8-8cb2-53ca1c164769.png)

**Comment by CSMR-DB** [comment]
Faced with the exact same issue as mentioned by @johnunclesam and @putuyoga. I am updating a specific Component's state whilst using a `Query` object in the `render()` method. Roughly looking like this:

```
class CloudMutations extends Component 
{
	constructor( props ) 
	{
		super( props );

		this._setActiveData = this._setActiveData.bind( this );

		this.state = { currentActiveData : 0 };
	}

	_setActiveData( dataIndex ) 
	{
		// console.log( "Page _setActiveData() as prop" );
		this.setState( { currentActiveData : dataIndex } );
	}

	render() 
	{
		return (
			<Query query={GET_DATA}>
				{( {
					loading, error, data 
				} ) => 
				{
					if ( loading ) return null;
					if ( error ) return <div>Error!</div>;

					const { CombinedMetrics } = data;
					const flattenedCloudData = CombinedMetrics.map( entry =>
						flattenObject( entry )
					);
					const cloudCodes = Object.keys(
						CombinedMetrics[CombinedMetrics.length - 1]
							.WhiteLabelMetrics
					).filter( key => key.length === 3 );

					return (
						<Grid
							templateAreas={`
							"header header header header"
							"card-1 card-2 card-3 card-4"
							"card-5 card-6 card-7 card-8"
							"card-9 card-10 card-11 card-12"
						`}
						>
							<Card gridArea={"header"}>
								<Vizzy
									data={flattenedCloudData}
									filter={[ "WhiteLabelMetrics.TotalNrOfLivePropertiesWithOTAs" ]}
									xAxisFieldName={"DateQueried"}
									_setActiveData={this._setActiveData}
									currentActiveData={
										this.state.currentActiveData
									}
								>
									<VizzyHeader
										title={"Live Properties Total"}
									/>
									<VizzySVG>
										<Line
											field={
												"WhiteLabelMetrics.TotalNrOfLivePropertiesWithOTAs"
											}
											isArea
										/>
										<Bars
											field={
												"WhiteLabelMetrics.TotalNrOfLivePropertiesWithOTAs"
											}
											isHelper
										/>
									</VizzySVG>
									<VizzyLegend />
								</Vizzy>
							</Card>
							{cloudCodes.map( ( code, i ) => (
								<Card gridArea={`card-${i + 1}`} key={i}>
									<Vizzy
										data={flattenedCloudData}
										filter={[ `WhiteLabelMetrics.${code}.NrOfLivePropertiesWithOTAs` ]}
										xAxisFieldName={"DateQueried"}
										currentActiveData={
											this.state.currentActiveData
										}
									>
										<VizzyHeader
											title={`Live Properties on ${code}`}
										/>
										<VizzySVG>
											<Line
												field={`WhiteLabelMetrics.${code}.NrOfLivePropertiesWithOTAs`}
												isArea
											/>
											<Bars
												field={`WhiteLabelMetrics.${code}.NrOfLivePropertiesWithOTAs`}
												isHelper
											/>
										</VizzySVG>
										<VizzyLegend />
									</Vizzy>
								</Card>
							) )}
						</Grid>
					);
				}}
			</Query>
		);
	}
}
```

The `_setActiveData` gets called `onMouseEnter` inside of the nested graph Component named "Vizzy". The only Component adjusting the state is the first graph, all the other graphs just need the changed state to be passed to them. This is generally giving me pretty poor rendering performance.

**Comment by johnunclesam** [comment]
@CSMR-DB please beautify your code or delete it an link external.

**Comment by vkolova** [comment]
Same problem here. Component's updating with no props or state changes, according to `why-did-you-update`. I tried changing it to use `withApollo` but still get same result.

**Comment by AkshayCloudAnalogy** [comment]
I am facing the same issue.
Anyone found any workaround?
