### ISSUE TITLE
Apollo MockedProvider with client directives

### ISSUE THREAD

**Issue by KamalAman** [apollographql/react-apollo#2508]
**Intended outcome:**
When using a MockedProvider and a query with client directives, the client directives should resolve

**Actual outcome:**

Client directives are unrecognized and console warns a message. There does not seem a way to specify apollo-link-state on the MockedProvider, which means any component using a client directive in its query is not really testable.

**How to reproduce the issue:**
Use a @client in a query, and then run the mockedProvider, the client directive will not be resolved.  

**Version**

- apollo-client@2.4.2
- react-apollo@2.1.9

**Comment by jhpedemonte** [comment]
I was able to get this working using the `cache` property for `MockedProvider`. If set, it's used as the cache for the `ApolloClient` instance that is created. Here's some pseudo-code of what I got working:

```javascript
const cache = new InMemoryCache().restore({
  ROOT_QUERY: {
    someQueryName: {
      type: 'id',
      id: 'SOME-QUERY-NAME-ID',
      generated: false,
    },
  },
  'SOME-QUERY-NAME-ID': {
    a: 1,
    prop: true,
    or: 'hello',
    two: 3,
    __typename: 'SomeQuery',
  },
});

render(
  <MockedProvider cache={cache}>
    <ComponentWhichMakesSomeQuery />
  </MockedProvider>
);
```

(Hope that makes sense)

**Comment by city41** [comment]
When using apollo-client 2.4.8 and react-apollo 2.4.0, MockedProvider handled `@client` directives correctly for us. Upon upgrading to 2.5.1, we find it now ignores them and does not resolve them.

I have a small query like this:
```
query isLoadingQuery {
    loadingStatus @client {
        isLoading
    }
}
```

and a test like

```
const mock = {
    request: {
        query: isLoadingQuery
    },
    result: {
        data: {
            loadingStatus: {
                isLoading: true
            }
        }
    }
};

// skipping this for now as react-apollo/apollo-client at 2.5.1+
// don't support @client directive in MockedProvider
describe('Pace', function() {
    it('should render pace when loading', function() {
        const wrapper = mount(
            <MockedProvider mocks={[mock]} addTypename={false}>
                <ApolloPace height={25} />
            </MockedProvider>
        );

        expect(wrapper.children().html()).toBeNull();

        return waitForExpect(() => {
            wrapper.update();
            expect(wrapper.children().html()).not.toBeNull();
        });
    });
});
```

This test used to pass before the upgrade. Now I can only get it to pass by removing `@client` directive from the query doc

**Comment by nshoes** [comment]
@city41 having the same issues. Asked on Spectrum a few days ago but no response :( @hwillson?

**Comment by nshoes** [comment]
Related: https://github.com/apollographql/graphql-tools/issues/916

**Comment by hwillson** [comment]
This was fixed in https://github.com/apollographql/react-apollo/pull/2524, and will be included in the next `react-apollo` release. We're hoping to push a new version out later today / tomorrow.

**Comment by nshoes** [comment]
Y A S

Awesome, thanks.

**Comment by nshoes** [comment]
@hwillson any chance it'll be released today?

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/react-apollo/pull/2524. Thanks!

**Comment by pdemarino** [comment]
I am still having this issue with this setup:

├─ @apollo/react-common@3.0.1
├─ @apollo/react-components@3.0.1
│  ├─ @apollo/react-common@^3.0.1
│  ├─ @apollo/react-hooks@^3.0.1
├─ @apollo/react-hoc@3.0.1
│  ├─ @apollo/react-common@^3.0.1
│  ├─ @apollo/react-components@^3.0.1
├─ @apollo/react-hooks@3.0.1
│  ├─ @apollo/react-common@^3.0.1
├─ @apollo/react-ssr@3.0.1
│  ├─ @apollo/react-common@^3.0.1
│  ├─ @apollo/react-hooks@^3.0.1
├─ @apollo/react-testing@3.0.1
│  ├─ @apollo/react-common@^3.0.1
├─ @apollographql/apollo-tools@0.4.0
│  └─ apollo-env@0.5.1
├─ @apollographql/graphql-playground-html@1.6.24
├─ apollo-boost@0.4.4
│  ├─ apollo-cache-inmemory@^1.6.3
│  ├─ apollo-cache@^1.3.2
│  ├─ apollo-client@^2.6.4
│  ├─ apollo-link-error@^1.0.3
│  ├─ apollo-link-http@^1.3.1
│  ├─ apollo-link@^1.0.6
├─ apollo-cache-control@0.8.1
│  ├─ apollo-server-env@2.4.1
├─ apollo-cache-inmemory@1.6.3
│  ├─ apollo-cache@^1.3.2
│  ├─ apollo-utilities@^1.3.2
├─ apollo-cache@1.3.2
│  ├─ apollo-utilities@^1.3.2
├─ apollo-client@2.6.4
│  ├─ apollo-cache@1.3.2
│  ├─ apollo-link@^1.0.0
│  ├─ apollo-utilities@1.3.2
├─ apollo-datasource@0.6.1
│  ├─ apollo-server-caching@0.5.0
│  └─ apollo-server-env@2.4.1
├─ apollo-engine-reporting-protobuf@0.4.0
├─ apollo-engine-reporting@1.4.3
│  ├─ apollo-engine-reporting-protobuf@0.4.0
│  ├─ apollo-graphql@^0.3.3
│  ├─ apollo-server-caching@0.5.0
│  ├─ apollo-server-env@2.4.1
│  ├─ apollo-server-types@0.2.1
│     ├─ @apollographql/apollo-tools@^0.4.0
│     ├─ apollo-server-env@2.4.1
│     └─ apollo-server-types@0.2.1
├─ apollo-env@0.5.1
├─ apollo-graphql@0.3.3
│  ├─ apollo-env@0.5.1
├─ apollo-link-error@1.1.11
│  ├─ apollo-link-http-common@^0.2.14
│  ├─ apollo-link@^1.2.12
├─ apollo-link-http-common@0.2.14
│  ├─ apollo-link@^1.2.12
├─ apollo-link-http@1.5.15
│  ├─ apollo-link-http-common@^0.2.14
│  ├─ apollo-link@^1.2.12
├─ apollo-link@1.2.12
│  ├─ apollo-utilities@^1.3.0
├─ apollo-server-caching@0.5.0
├─ apollo-server-core@2.8.1
│  ├─ @apollographql/apollo-tools@^0.4.0
│  ├─ @apollographql/graphql-playground-html@1.6.24
│  ├─ apollo-cache-control@0.8.1
│  ├─ apollo-datasource@0.6.1
│  ├─ apollo-engine-reporting@1.4.3
│  ├─ apollo-server-caching@0.5.0
│  ├─ apollo-server-env@2.4.1
│  ├─ apollo-server-errors@2.3.1
│  ├─ apollo-server-plugin-base@0.6.1
│  ├─ apollo-server-types@0.2.1
│  ├─ apollo-tracing@0.8.1
│  │  ├─ @apollographql/apollo-tools@^0.4.0
│  │  ├─ apollo-server-env@2.4.1
│  │  └─ apollo-server-types@0.2.1
├─ apollo-server-env@2.4.1
├─ apollo-server-errors@2.3.1
├─ apollo-server-lambda@2.8.1
│  ├─ @apollographql/graphql-playground-html@1.6.24
│  ├─ apollo-server-core@2.8.1
│  ├─ apollo-server-env@2.4.1
│  ├─ apollo-server-types@0.2.1
├─ apollo-server-plugin-base@0.6.1
│  └─ apollo-server-types@0.2.1
├─ apollo-server-types@0.2.1
│  ├─ apollo-engine-reporting-protobuf@0.4.0
│  ├─ apollo-server-caching@0.5.0
│  └─ apollo-server-env@2.4.1
├─ apollo-tracing@0.8.1
│  ├─ apollo-server-env@2.4.1
├─ apollo-utilities@1.3.2
│  ├─ @apollo/react-testing@^3.0.0
│  ├─ apollo-boost@^0.4.3
│  ├─ react-apollo@^3.0.0
│  ├─ apollo-server-lambda@^2.8.1
│  ├─ @apollographql/apollo-tools@^0.4.0
│  ├─ apollo-server-env@2.4.1
│  └─ apollo-server-types@0.2.1
│  ├─ apollo-link@^1.2.3
│  ├─ apollo-utilities@^1.0.1
├─ react-apollo@3.0.1
│  ├─ @apollo/react-common@^3.0.1
│  ├─ @apollo/react-components@^3.0.1
│  ├─ @apollo/react-hoc@^3.0.1
│  ├─ @apollo/react-hooks@^3.0.1
│  └─ @apollo/react-ssr@^3.0.1

**Comment by Paddy-Hamilton** [comment]
I am also seeing a @client warning and not the expected behaviour so my test fails
I have all the latest versions 


```
    "apollo-boost": "^0.4.4",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.12",
    "apollo-link-error": "^1.1.11",
    "apollo-link-http": "^1.5.15",
    "apollo-link-state": "^0.4.2",
    "@apollo/react-hooks": "^3.0.1",
    "@apollo/react-ssr": "^3.0.1",
    "@apollo/react-testing": "^3.0.1",
```

Query
```
query EDIT_CAKE_MODAL_OPEN {
  editCakeModalOpen @client
}
```

Test
```
import React from "react";
import "@testing-library/jest-dom/extend-expect";
import { render } from "@testing-library/react";
import { MockedProvider } from "@apollo/react-testing";
import { fakeCake } from "../../lib/testUtils";
import EditCakeModal from "./index";
const cake = fakeCake("ASD123");
const defaultProps = {
  ...cake
};
import { EDIT_CAKE_MODAL_OPEN } from "../../graphql/queries.graphql";

const mocks = [
  {
    request: {
      query: EDIT_CAKE_MODAL_OPEN
    },
    result: {
      data: {
        editCakeModalOpen: true
      }
    }
  }
];
describe("<EditCakeModal/>", () => {
  test("renders when open", () => {
    const { container, queryByLabelText } = render(
      <MockedProvider mocks={mocks} addTypename={false}>
        <EditCakeModal {...defaultProps} />
      </MockedProvider>
    );
    expect(queryByLabelText("Name")).not.toBeInTheDocument();

    expect(container).toMatchSnapshot();
  });
});
```

warning
`      Found @client directives in a query but no ApolloClient resolvers were specified. This means ApolloClient local resolver handling has been disabled, and @client directives will be passed through to your link chain.`

**Comment by DenVilden** [comment]
For someone who still experienced this problem, adding __typename solved it for me
