### ISSUE TITLE
getDataFromTree breaks React Hooks

### ISSUE THREAD

**Issue by pheuter** [apollographql/react-apollo#2541]
### [Related Issue](https://github.com/facebook/react/issues/13972)

Rendering the app tree during `getDataFromTree(<App />)` appears to break React Hooks, causing an invariant violation to be thrown.

```
UnhandledPromiseRejectionWarning: Invariant Violation: Hooks can only be called inside the body of a function component.
        |     at invariant (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react/cjs/react.development.js?:125:15)
        |     at resolveDispatcher (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react/cjs/react.development.js?:1450:28)
        |     at useState (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react/cjs/react.development.js?:1473:20)
```

Rendering the same app tree using `renderToString(<App />)` works just fine.

**react-apollo** - v2.2.4
**apollo-boost** - v0.1.17
**react** - v16.7.0-alpha.0
**react-dom** - v16.7.0-alpha.0
**graphql** - v14.0.2

**Comment by benjamn** [comment]
See https://github.com/apollographql/react-apollo/pull/2533.

**Comment by benjamn** [comment]
Fixed in `react-apollo@2.3.1`!

**Comment by mhaagens** [comment]
Works with react@16.7.0-alpha.2, but breaks with react@16.7.0.

**Comment by r281GQ** [comment]
Hey guys, 

I have react-apollo@2.3.3 (tried it with next and 2.3.1) with react && reactDom 16.7.alpha.2 and getDataFrom still fails on the server. Is there anything  I might have missed?

Cheers!

**Comment by nicolasrenon** [comment]
Having the same issue with React 16.8.4 and @apollo/react-ssr.

Looking at this thread https://github.com/facebook/react/issues/14022#issuecomment-515755059 make me anxious. Is there really no solution?
