### ISSUE TITLE
writeQuery support?

### ISSUE THREAD

**Issue by richardgirges** [apollographql/react-apollo#568]
Hey there Apollo team. Fantastic work so far! We're about to go to production with our first GraphQL/Apollo based application!

We're currently transitioning from a very redux-heavy app to GraphQL. So until we have time to fully vet and move over to GraphQL subscriptions, we're finding ourselves needing to write data to the store from Socket.io-based events in our app.

We're attempting to use `writeQuery()` but it doesn't seem to work with react-apollo.

## Steps to Reproduce
1. Bring in your Apollo Client to your HOC:
```
@withApollo
```

2. Retrieve a cached query then update it:
```javascript
const CHAT_ROOM_QUERY = gql`
  query ChatRoomQuery {
    chatRoom($chatroom_id: Int!) {
      chatRoom(chatroom_id: $chatroom_id) {
        chatroom_id
        messages
      }
    }
  }
`;

try {
  // Retrieve cached query data
  const chatRoomData = client.readQuery({
    query: CHAT_ROOM_QUERY,
    variables: { chatroom_id: 123 }
  });

  // This outputs data as expected
  console.log('messages', chatRoomData.messages);

  // Add new message to messages array
  chatRoomData.messages.push({
    message_id: 999,
    body: 'Hello'
  });

  // Update cached query
  client.writeQuery({
    query: CHAT_ROOM_QUERY,
    variables: { chatroom_id: 123 },
    data: chatRoomData
  });
} catch (e) {
  console.warn(e);
}
```

3. Nothing happens. No errors, no store update.
The cached query doesn't get updated as I would expect it to with `updateQueries`.

Am I doing something wrong or is writeQuery simply not supported in react-apollo yet?

As a last resort, I added the following right after the `writeQuery` call, but no dice. The query still doesn't get updated with the new message:
```javascript
client.query({
  query: CHAT_ROOM_QUERY,
  variables: { chatroom_id: 123 },
  fetchPolicy: 'cache-first'
})
```

### Version
-  "react-apollo": "^1.0.0-rc.3"

**Comment by stubailo** [comment]
That definitely looks like something that should work! It would help us resolve things faster if there was a simple app we could try running.

**Comment by richardgirges** [comment]
Simple app, coming right up. Will have it ready for ya by tomorrow.

Thanks for the quick response!

**Comment by ndonnipa** [comment]
have you found a way to solve this? i'm facing the same issue

**Comment by richardgirges** [comment]
@ndonnipa no not working for me yet. At the moment, I'm going with the heavy-handed approach of refetching any cached queries.

Apologies, I got sidetracked with work and haven't had a chance to create a sample app to demonstrate the behavior I'm seeing. I will try to get one up today.

**Comment by helfer** [comment]
@richardgirges Can you show me the code that you use to initialize the client? I think it might have to do with `dataIdFromObject` and the fact that `readQuery` and `writeQuery` don't automatically add `__typename`. You could also check this by adding `__typename` to your query at every level.

**Comment by richardgirges** [comment]
@helfer yep here it is:

```
const client = new ApolloClient({
  networkInterface: createNetworkInterface({ uri: `${config.apiUrl}/ql` }),
  addTypename: true,
  dataIdFromObject: result => {
    const snakeType = snakeCase(result.__typename);
    const idSuffix = '_id';

    if (result.__typename && result.id)
      return result.__typename + result.id;

    if (result.__typename && result[snakeType + idSuffix])
      return result.__typename + result[snakeType + idSuffix];

    return null;
  }
});
```

Just to be clear, you're suggesting I should try explicitly adding `__typename` to all of the queries I execute through `@graphql` and the client?

Thanks!

**Comment by helfer** [comment]
@richardgirges Ok, I see. I'm not 100% sure, but my hypothesis is that the problem is related to the fact that the writeQuery and readQuery functions currently don't apply the addTypename transform.
That means when you write your objects back, they don't end up under the same id as your previous ones because of dataIdFromObject. I don't want you to have to add __typename manually to all your queries, but it would be great if you could try it for this one query to see if it's a workaround for the problem until a fix can be implemented.

**Comment by richardgirges** [comment]
@helfer we're getting somewhere. I added `__typename` to every level of the query and now at least `writeQuery()` is causing some sort of effect. I'm not seeing the query actually get updated with the data I'm passing into `writeQuery()`, but instead the data is being completely cleared from the query's data object. So `this.props.data` ends up looking like this:

**Comment by helfer** [comment]
@richardgirges could you try this again with the most recent version of react-apollo and apollo-client? I think it should be fixed now.

**Comment by richardgirges** [comment]
@helfer I'm still seeing the same issue, but I'm not 100% sure I've downloaded the correct version of react-apollo and apollo-client. 

I'm on the following versions:

```
"apollo-client": "^1.0.2",
"react-apollo": "^1.0.0",
```

Should I pull down a specific branch from github instead in my `package.json`?

Thanks!

**Comment by yattias** [comment]
@richardgirges @helfer I confirmed that this is an issue on `"react-apollo": "^1.0.0-rc.3"`.

It is fixed on `"react-apollo": "^1.0.0-rc.2"` with `"apollo-client": "^1.0.1"`

One important note: There is a typo on the [Direct Cache Access Docs](http://dev.apollodata.com/core/read-and-write.html#writequery-and-writefragment). The `query` field is necessary or else an error will be thrown.

I submitted a [PR against the core-docs](https://github.com/apollographql/core-docs/pull/272)

https://github.com/apollographql/core-docs/pull/272
