### ISSUE TITLE
catch unhandled query errors

### ISSUE THREAD

**Issue by reut-co** [apollographql/react-apollo#644]
I can't find a way to catch query errors so I'm getting red box errors of react native... I can only catch mutation errors..

**Comment by helfer** [comment]
Hi @reut-co. If you check the `error` prop and handle it, there shouldn't be a red box. If you're already doing that, could you provide more details so we can try to help?

**Comment by reut-co** [comment]
The problem was solved when switching the order of the checks: loading & error.. 
I first had to check for an error:
if (error){..}
else if (loading){...}

**Comment by helfer** [comment]
Oooh, that's a really good point! We should include that in all our documentation. Would you mind making a PR to https://github.com/apollographql/react-docs to add the information?

Ideally I think the information belongs in this section: http://dev.apollodata.com/react/queries.html#default-result-props

**Comment by NazarYablonskiy** [comment]
@helfer I do handle errors in the described way, but I still get red box errors of react native when a component is unmounting

**Comment by arrowfunxtion** [comment]
Same problem here

**Comment by lxcid** [comment]
Same thing for me as well, +1

**Comment by lxcid** [comment]
Just want to add that none of the solution at https://github.com/apollographql/react-apollo/issues/604#issuecomment-355648596 work for me.

I handled, the error but as long as I unmount my error handling component, I receive unhandled error.

**Comment by lxcid** [comment]
Since there's more than 1 report? Should this ticket be open?

**Comment by AndreyMalykhin** [comment]
+1
