### ISSUE TITLE
Flow types cause errors with Components that are not stateless

### ISSUE THREAD

**Issue by Strayer** [apollographql/react-apollo#900]
**Intended outcome:**
It should be possible to create React.Component classes that have a state and are type-checked with the included Flow types.

**Actual outcome:**

Creating a Component class that has a State will result in Flow errors:

```
type AllTrips = Array<{id: string}>;
type Response = { allTrips: AllTrips };
type State = { counter: number };

class TheGraphQLThing extends PureComponent {
    props: ChildProps<{}, Response>;
    state: State = {
        counter: 0,
    };
    
    render() {
        const {
            loading,
            allTrips,
        } = this.props.data;
        
        const {
            counter,
        } = this.state;
        
        if (loading) {
            return <Text>Loading</Text>;
        }

        return (
            <View style={{alignItems: "center", justifyContent: "center"}}>
                <Text>Number of trips: {allTrips.length}</Text>
                <Button
                    onPress={() => this.setState({ counter: counter + 1 })}
                    title={`Increment ${counter} to ${counter+1}`}
                />
            </View>
        );
    }
}

const withQuery: OperationComponent<Response> = graphql(
    gql`query { allTrips { id } }`
);
const TheGraphQLThingContainer = withQuery(TheGraphQLThing);
```

```
app.js:54
 54: const TheGraphQLThingContainer = withQuery(TheGraphQLThing);
                                                ^^^^^^^^^^^^^^^ class type: TheGraphQLThing. This type is incompatible with
             v-------------------------------
112:       | StatelessComponent<TMergedProps>
113:       | Class<React$Component<void, TMergedProps, void>>
           -------------------------------------------------^ union: type application of polymorphic type: type `StatelessComponent` | class type: type application of identifier `React$Component`. See: node_modules/react-apollo/react-apollo.umd.js.flow:112
  Member 1:
  112:       | StatelessComponent<TMergedProps>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type application of polymorphic type: type `StatelessComponent`. See: node_modules/react-apollo/react-apollo.umd.js.flow:112
  Error:
  112:       | StatelessComponent<TMergedProps>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. Callable signature not found in. See: node_modules/react-apollo/react-apollo.umd.js.flow:112
   54: const TheGraphQLThingContainer = withQuery(TheGraphQLThing);
                                                  ^^^^^^^^^^^^^^^ statics of TheGraphQLThing
  Member 2:
  113:       | Class<React$Component<void, TMergedProps, void>>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: type application of identifier `React$Component`. See: node_modules/react-apollo/react-apollo.umd.js.flow:113
  Error:
   21:     state: State = {
                  ^^^^^ object type. This type is incompatible with
  113:       | Class<React$Component<void, TMergedProps, void>>
                                                         ^^^^ undefined. See: node_modules/react-apollo/react-apollo.umd.js.flow:113
```

**How to reproduce the issue:**

Reproduced in this repo: https://github.com/Strayer/ApolloFlowIssues/tree/component-with-state
Install dependencies, then run yarn run flow to see the errors.

**Version**
- apollo-client@1.9.0-1
- react-apollo@1.4.8

**Comment by michielbouw** [comment]
Hi, have the exact same problem with flow type checks, just updated to newest apollo-client from version 1.7.0 and react-apollo from version 1.4.6. For apollo-client@1.7.0 and react-apollo@1.4.6 all still works fine. Updating only one of them (doesnt matter which) also has the same issue.

**Version when error**
- apollo-client@1.8.1 (but 1.9.0-1 has same result)
- react-apollo@1.4.8

Changelogs for both libs say "Add support for flow typecheck to work out of the box (without any configuration)" but that doesn't seems to be true.

Is there some config we are missing?

**Comment by benhjames** [comment]
Looks fixed in 1.4.12! 😃

**Comment by Strayer** [comment]
Can confirm, `yarn upgrade apollo-client react-apollo` to react-apollo@1.4.12 and apollo-client@1.9.1 seems to fix this.

**Comment by richardgirges** [comment]
I'm still seeing this w/ react-apollo@1.4.12 and apollo-client@1.9.1 but only when I use `withApollo`. It no longer shows up when using the `graphql` container.

**Comment by michielbouw** [comment]
Updated to latest react-apollo@1.4.15 and apollo-client@1.9.2 and flow-bin@0.46.0. 

Issue still occurring for me. I only use the `graphql` containers, do not use `withApollo`.
Maybe it has something to do with not updating flow-bin to the latest. But I have some other deps that cannot handle updating flow-bin right now.

**Comment by richardgirges** [comment]
I'm still seeing this issue when using `withApollo`. Work around for now is to add `// $FlowFixMe` flags above any usage of `withApollo` but this disables type checking for that HOC. :(
